16:44:18:1097733839:ya_zloo__None:ya_zloo:en:HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6616517747:AAGT10sGkVKKqUAgnfLYV3UTQpnIl0UjCF4/getFile?file_id=AwACAgIAAxkBAAMJZew9cikMiaYpxjjmt0Alxpq7uvEAAi5JAAJ4PnhKa9nk1_bzgoc0BA (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002B617906CF0>, 'Connection to api.telegram.org timed out. (connect timeout=15)'))
